config/routes.rb
Rails.application.routes.draw do
  root "static_pages#welcome"
  resources :commands
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/command.rb
class Command < ApplicationRecord
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/commands_controller.rb
class CommandsController < ApplicationController
  before_action :set_command, only: [:show, :edit, :update, :destroy]

  def index
    @commands = Command.all
  end

  def show
  end

  def new
    @command = Command.new
  end

  def create
    @command = Command.new(command_params)

    if @command.save
      redirect_to commands_path, notice: "Your command was saved successfully."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @command.update(command_params)
      redirect_to commands_path, notice: "Your command was updated successfully."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @command.destroy
    redirect_to commands_path, notice: "Your command was destroyed successfully."
  end

  private

  def set_command
    @command = Command.find(params[:id])
  end

  def command_params
    params.require(:command).permit(:name)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def welcome
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commands_helper.rb
module CommandsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/commands/_command.html.erb
<%# app/views/commands/_command.html.erb %>

<div class="command">
  <%= link_to command.name, command_path(command) %>
  <div class="command__actions">
    <%= button_to "Delete",
                  command_path(command),
                  method: :delete,
                  class: "btn btn--light" %>
    <%= link_to "Edit",
                edit_command_path(command),
                class: "btn btn--light" %>
  </div>
</div>

app/views/commands/_form.html.erb
<%= simple_form_for command, html: { class: "command form" } do |f| %>
  <% if command.errors.any? %>
    <div class="error-message">
      <%= command.errors.full_messages.to_sentence.capitalize %>
    </div>
  <% end %>

  <%= f.input :name, input_html: { autofocus: true } %>
  <%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/commands/edit.html.erb
<%# app/views/commands/edit.html.erb %>

<main class="container">
  <%= link_to sanitize("&larr; Back to command"), command_path(@command) %>

  <div class="header">
    <h1>Edit Command</h1>
  </div>

  <%= render "form", command: @command %>
</main>

app/views/commands/index.html.erb
<main class="container">
  <div class="header">
    <h1>Commands</h1>
      <%= link_to "New Command",
                  new_command_path,
                  class: "btn btn--primary" %>
  </div>

  <%= render @commands %>
</main>

app/views/commands/new.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to Commands"), commands_path %>

  <div class="header">
    <h1>New Command</h1>
  </div>

  <%= render "form", command: @command %>
</main>

app/views/commands/show.html.erb
<main class="container">
  <%= link_to sanitize("&larr; Back to Commands"), commands_path %>
  <div class="header">
    <h1>
      <%= @command.name %>
    </h1>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Commandify</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/static_pages/welcome.html.erb
  <div class="landing">
    <h1>Hey Tim, Welcome to Commandify.</h1>
  </div>

  <div class="landing">
    <h2>Please Log in, Enter Your Command, and Save It!</h2>
  </div>

  <div class="landing">
    <%= link_to "Login",
                "#",
                class: "btn btn--primary" %>


    <%= link_to "New Command",
                new_command_path,
                class: "btn btn--primary" %>
  </div>